# Generated by Django 4.1 on 2024-03-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sponsorship-img')),
                ('name', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=250)),
                ('age', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'sponsorships',
            },
        ),
    ]
