# Generated by Django 4.1 on 2024-03-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Galleries'},
        ),
    ]
