# Generated by Django 4.1 on 2024-03-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=225, null=True)),
                ('states', models.CharField(blank=True, max_length=225, null=True)),
                ('zipcode', models.CharField(max_length=225)),
                ('volunteer_position', models.CharField(max_length=50)),
                ('volunteer_experience', models.TextField()),
                ('volunter_skills', models.CharField(max_length=225)),
                ('training_and_decrees_received', models.CharField(max_length=300)),
                ('reason_for_volunteer', models.TextField(blank=True, null=True)),
                ('references', models.TextField()),
                ('datetime_available', models.CharField(max_length=250)),
                ('emergency_contact', models.CharField(max_length=300)),
                ('criminal_conviction', models.CharField(blank=True, max_length=300, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('signature', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'volunteer appliction',
                'ordering': ['-date'],
            },
        ),
    ]
