# Generated by Django 4.1 on 2024-03-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_volunteerapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryCategory',
        ),
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'gallery categories'},
        ),
    ]
