# Generated by Django 4.1 on 2024-03-13 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0008_rename_gallery_gallerycategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='each_gallery_imgs')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.gallerycategory')),
            ],
            options={
                'verbose_name_plural': 'galleries',
                'ordering': ['-date_added'],
            },
        ),
    ]
