# Generated by Django 4.1 on 2024-03-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0009_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'galleries'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='date_added',
        ),
    ]
