# Generated by Django 4.1 on 2024-03-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0010_alter_gallery_options_remove_gallery_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycategory',
            name='date_added',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
