# Generated by Django 4.1 on 2024-03-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0011_alter_gallerycategory_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerapplication',
            old_name='volunter_skills',
            new_name='volunteer_skills',
        ),
    ]
