# Generated by Django 4.1 on 2024-03-13 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0012_rename_volunter_skills_volunteerapplication_volunteer_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerapplication',
            old_name='Address',
            new_name='address',
        ),
    ]
