# Generated by Django 4.1 on 2024-03-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0013_rename_address_volunteerapplication_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
