# Generated by Django 4.1 on 2024-03-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0014_gallerycategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='verified',
            field=models.CharField(max_length=3),
        ),
    ]
