# Generated by Django 4.1 on 2024-03-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0015_alter_volunteerapplication_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='USAProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='usproj-img')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'usaproject',
                'ordering': ['-date_added'],
            },
        ),
    ]
