# Generated by Django 4.1 on 2024-03-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0016_usaproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhanaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='ghproj-img')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ghanaproject',
                'ordering': ['-date_added'],
            },
        ),
        migrations.AlterModelOptions(
            name='usaproject',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'USAproject'},
        ),
    ]
