# Generated by Django 4.1 on 2024-03-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0019_alter_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='main_category',
        ),
    ]
