# Generated by Django 4.1 on 2024-03-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0020_rename_title_project_main_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
