# Generated by Django 4.1 on 2024-03-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0021_delete_project_delete_projectcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project_title', models.CharField(max_length=250)),
                ('project_content', models.TextField()),
                ('home_content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('date_added', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'project categories',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='usproj-img')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.projectcategory')),
            ],
            options={
                'verbose_name_plural': 'projects',
                'ordering': ['-date_added'],
            },
        ),
    ]
