# Generated by Django 4.1 on 2024-03-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0028_projectcategory_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
