# Generated by Django 4.1 on 2024-03-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0031_alter_usacategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ghanacategory',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'Ghana category'},
        ),
    ]
