# Generated by Django 4.1 on 2024-03-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0032_alter_ghanacategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ghanaproject',
            options={'verbose_name_plural': 'ghana projects'},
        ),
        migrations.RemoveField(
            model_name='ghanaproject',
            name='date_added',
        ),
    ]
