# Generated by Django 4.1 on 2024-03-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentoption',
            name='payment_method',
        ),
    ]
