# Generated by Django 4.1 on 2024-03-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_paymentoption_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentoption',
            options={'ordering': ['-date_donated'], 'verbose_name_plural': 'payment option'},
        ),
        migrations.RenameField(
            model_name='paymentoption',
            old_name='date_created',
            new_name='date_donated',
        ),
        migrations.RenameField(
            model_name='paymentoption',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='paymentoption',
            old_name='amount',
            new_name='user_amount',
        ),
        migrations.RenameField(
            model_name='paymentoption',
            old_name='country',
            new_name='user_country',
        ),
        migrations.RenameField(
            model_name='paymentoption',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='paymentoption',
            old_name='phone',
            new_name='user_phone',
        ),
    ]
