# Generated by Django 4.1 on 2024-03-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paymentoption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoption',
            name='payment_option',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
